## Test App

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import neurokit2 as nk
import json
import csv

import tkinter as tk
from tkinter import ttk
from tkinter import filedialog
from tkinter import messagebox
from tkinter import simpledialog
from tkinter import colorchooser
from tkinter import font
from tkinter import simpledialog
from tkinter import scrolledtext

import customtkinter as ctk

import os
import sys
import datetime
import time
import re


# load data
def load_data2():
    file1, file2 = tk.filedialog.askopenfilename(title='Select files to load', filetypes=[('CSV files', '*.csv'), ('JSON files', '*.json'), ('Text files', '*.txt'), ('Excel files', '*.xlsx'), ('Excel files', '*.xls')], multiple=True)
    tk.Tk().withdraw()
    
    if not file1 and not file2:
        return None
    dataset = []
    try:
        for file in [file1, file2]:
            if file.endswith('.csv'):
                data = pd.fread(file)
            elif file.endswith('.json'):
                with open(file, 'r') as f:
                    data = json.load(f)
            elif file.endswith('.txt'):
                with open(file, 'r') as f:
                    data = f.read()
            elif file.endswith('.xlsx'):
                data = pd.read_excel(file)
            elif file.endswith('.xls'):
                data = pd.read_excel(file)
            else:
                data = None
            dataset.append(data)
        return dataset
            
    except Exception as e:
        print(e)
        return None

In [4]:

def load_data1():
    file = tk.filedialog.askopenfilename(title='Select file to load')
    tk.Tk().withdraw()
    if not file:
        return None
    try:
        if file.endswith('.csv'):
            data = pd.read_csv(file)
        elif file.endswith('.json'):
            with open(file, 'r') as f:
                data = json.load(f)
        elif file.endswith('.txt'):
            with open(file, 'r') as f:
                data = f.read()
        elif file.endswith('.xlsx'):
            data = pd.read_excel(file)
        elif file.endswith('.xls'):
            data = pd.read_excel(file)
        else:
            data = None
        return data
    except Exception as e:
        print(e)
        return None

In [68]:
df1 = r'/Users/edeneldar/Library/CloudStorage/GoogleDrive-admonlab_edene_hipaa@labs.hevra.haifa.ac.il/תיקיות אחסון שיתופי/Hevra - Roy Salomon Lab - HIPAA/SafeHeart_research_(NovaHelp)/Experiment/Data/sub_119/FITBIT/Sleep/sleep-2023-12-30.json'
df2 = r'/Users/edeneldar/Library/CloudStorage/GoogleDrive-admonlab_edene_hipaa@labs.hevra.haifa.ac.il/תיקיות אחסון שיתופי/Hevra - Roy Salomon Lab - HIPAA/SafeHeart_research_(NovaHelp)/Experiment/Data/sub_119/FITBIT/Sleep/sleep-2024-01-29.json'

df4 = r'/Users/edeneldar/Library/CloudStorage/GoogleDrive-admonlab_edene_hipaa@labs.hevra.haifa.ac.il/תיקיות אחסון שיתופי/Hevra - Roy Salomon Lab - HIPAA/SafeHeart_research_(NovaHelp)/Experiment/Data/sub_120/FITBIT/Sleep/sleep-2023-12-30.json'
df5 = r'/Users/edeneldar/Library/CloudStorage/GoogleDrive-admonlab_edene_hipaa@labs.hevra.haifa.ac.il/תיקיות אחסון שיתופי/Hevra - Roy Salomon Lab - HIPAA/SafeHeart_research_(NovaHelp)/Experiment/Data/sub_120/FITBIT/Sleep/sleep-2024-01-29.json'

with open(df1, 'r') as f:
    df1 = json.load(f)
    
with open(df2, 'r') as f:
    df2 = json.load(f)

with open(df4, 'r') as f:
    df4 = json.load(f)
    
with open(df5, 'r') as f:
    df5 = json.load(f)
    
len(df1), len(df2), len(df4), len(df5)

(19, 16, 16, 21)

In [69]:
df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)

df4 = pd.DataFrame(df4)
df5 = pd.DataFrame(df5)

In [70]:
# chain data together
def chain_data(df1, df2):
    return pd.concat([df1, df2], axis=0)

def chain_data_H(df1, df2):
    return pd.concat([df1, df2], axis=1)

In [111]:

df3 = chain_data(df1, df2)

df6 = chain_data(df4, df5)

df3['dateOfSleep_119'] = pd.to_datetime(df3['dateOfSleep'])
df6['dateOfSleep_120'] = pd.to_datetime(df6['dateOfSleep'])

df3['startTime_119'] = pd.to_datetime(df3['startTime'])
df6['startTime_120'] = pd.to_datetime(df6['startTime'])

df3['endTime_119'] = pd.to_datetime(df3['endTime'])
df6['endTime_120'] = pd.to_datetime(df6['endTime'])

dates = pd.date_range(start='2024-01-15', end='2024-02-22', freq='D')
dates = pd.to_datetime(dates)
dates = pd.DataFrame(dates, columns=['date'])

# merge dataframes on date
df3 = pd.merge(df3, dates, left_on='dateOfSleep_119', right_on='date', how='right')
df6 = pd.merge(df6, dates, left_on='dateOfSleep_120', right_on='date', how='right')
df7 = pd.DataFrame()
df7['date'] = dates['date']

df3_time = pd.DataFrame()
df6_time = pd.DataFrame()

df3_time = df3[['date', 'dateOfSleep_119', 'startTime_119', 'endTime_119']]
df6_time = df6[['date', 'dateOfSleep_120', 'startTime_120', 'endTime_120']]

df7 = pd.merge(df7, df3_time, on='date', how='left')
df7 = pd.merge(df7, df6_time, on='date', how='left')

df7['startTime_119'] = df7['startTime_119'].dt.time
df7['endTime_119'] = df7['endTime_119'].dt.time

df7['startTime_120'] = df7['startTime_120'].dt.time
df7['endTime_120'] = df7['endTime_120'].dt.time


df7

,date,dateOfSleep_119,startTime_119,endTime_119,dateOfSleep_120,startTime_120,endTime_120
0,2024-01-15,NaT,NaT,NaT,NaT,NaT,NaT
1,2024-01-16,2024-01-16,02:37:30,09:46:30,2024-01-16,01:46:00,09:59:00
2,2024-01-17,2024-01-17,02:41:30,09:59:00,2024-01-17,02:39:00,08:00:30
3,2024-01-18,2024-01-18,11:40:30,13:00:30,2024-01-18,02:22:00,09:42:30
4,2024-01-18,2024-01-18,02:29:30,09:49:00,2024-01-18,02:22:00,09:42:30
5,2024-01-19,2024-01-19,17:25:00,18:37:30,2024-01-19,17:25:30,18:37:30
6,2024-01-19,2024-01-19,17:25:00,18:37:30,2024-01-19,01:48:00,09:02:30
7,2024-01-19,2024-01-19,01:45:00,09:06:00,2024-01-19,17:25:30,18:37:30
8,2024-01-19,2024-01-19,01:45:00,09:06:00,2024-01-19,01:48:00,09:02:30
9,2024-01-20,2024-01-20,06:16:30,13:11:00,2024-01-20,06:09:00,13:20:00
10,2024-01-21,2024-01-21,15:12:30,17:36:30,2024-01-21,01:13:00,05:59:30
11,2024-01-21,2024-01-21,01:13:00,05:52:30,2024-01-21,01:13:00,05:59:30
12,2024-01-22,2024-01-22,00:54:30,11:49:00,2024-01-22,00:44:00,08:02:30
13,2024-01-23,2024-01-23,11:18:30,13:54:30,2024-01-23,01:39:00,08:03:00
14,2024-01-23,2024-01-23,01:37:30,07:50:00,2024-01-23,01:39:00,08:03:00
15,2024-01-24,2024-01-24,15:20:00,17:27:30,2024-01-24,08:39:00,09:51:00
16,2024-01-24,2024-01-24,15:20:00,17:27:30,2024-01-24,01:10:00,07:26:00
17,2024-01-24,2024-01-24,01:23:00,07:15:00,2024-01-24,08:39:00,09:51:00
18,2024-01-24,2024-01-24,01:23:00,07:15:00,2024-01-24,01:10:00,07:26:00
19,2024-01-25,2024-01-25,01:10:30,11:16:30,2024-01-25,01:01:30,08:06:30
20,2024-01-26,2024-01-26,03:49:00,10:02:00,2024-01-26,03:46:00,10:08:30
21,2024-01-27,2024-01-27,03:57:00,11:56:00,2024-01-27,03:07:30,11:56:00
22,2024-01-28,2024-01-28,02:23:00,12:56:00,2024-01-28,02:22:00,08:04:30
23,2024-01-29,2024-01-29,01:17:30,15:40:00,2024-01-29,01:21:30,08:12:00
24,2024-01-29,2024-01-29,01:17:30,15:40:00,2024-01-29,01:21:30,08:12:00
25,2024-01-29,2024-01-29,01:17:30,15:40:00,2024-01-29,01:21:30,08:12:00
26,2024-01-29,2024-01-29,01:17:30,15:40:00,2024-01-29,01:21:30,08:12:00
27,2024-01-30,2024-01-30,01:26:30,11:24:00,2024-01-30,01:25:00,08:02:30
28,2024-01-31,2024-01-31,01:05:30,11:52:30,2024-01-31,00:48:00,07:59:00
29,2024-02-01,2024-02-01,02:47:30,14:00:00,2024-02-01,02:45:30,08:32:30
30,2024-02-02,2024-02-02,03:46:00,12:39:00,2024-02-02,03:14:00,12:39:00
31,2024-02-03,2024-02-03,05:00:00,13:17:30,2024-02-03,04:47:30,13:22:00
32,2024-02-04,2024-02-04,02:41:30,06:28:30,2024-02-04,02:31:30,07:49:30
33,2024-02-05,2024-02-05,01:24:00,13:15:00,2024-02-05,01:24:00,08:01:00
34,2024-02-06,2024-02-06,07:52:00,10:26:30,2024-02-06,03:39:00,06:01:30
35,2024-02-06,2024-02-06,03:39:30,05:55:00,2024-02-06,03:39:00,06:01:30
36,2024-02-07,2024-02-07,21:39:00,05:55:30,2024-02-07,21:30:00,05:56:30
37,2024-02-08,2024-02-08,23:47:00,06:23:30,2024-02-08,23:41:00,07:19:00
38,2024-02-09,2024-02-09,00:37:30,07:50:30,2024-02-09,00:23:00,07:36:30
39,2024-02-10,2024-02-10,20:37:00,21:39:00,2024-02-10,05:44:00,10:41:00
40,2024-02-10,2024-02-10,05:42:30,10:41:30,2024-02-10,05:44:00,10:41:00
41,2024-02-11,2024-02-11,04:42:00,08:33:00,NaT,NaT,NaT
42,2024-02-12,NaT,NaT,NaT,NaT,NaT,NaT
43,2024-02-13,NaT,NaT,NaT,NaT,NaT,NaT
44,2024-02-14,NaT,NaT,NaT,NaT,NaT,NaT
45,2024-02-15,NaT,NaT,NaT,NaT,NaT,NaT
46,2024-02-16,NaT,NaT,NaT,2024-02-16,05:05:00,10:43:00
47,2024-02-17,NaT,NaT,NaT,2024-02-17,03:32:00,08:56:00
48,2024-02-18,NaT,NaT,NaT,2024-02-18,08:16:00,10:31:00
49,2024-02-18,NaT,NaT,NaT,2024-02-18,21:44:30,00:51:30
50,2024-02-19,NaT,NaT,NaT,2024-02-19,19:46:00,22:56:30
51,2024-02-19,NaT,NaT,NaT,2024-02-19,00:57:30,07:52:00
52,2024-02-20,NaT,NaT,NaT,2024-02-20,13:17:30,23:54:00
53,2024-02-21,NaT,NaT,NaT,NaT,NaT,NaT
54,2024-02-22,NaT,NaT,NaT,2024-02-22,17:10:00,00:32:30

In [113]:
df7.to_excel('sleep_data.xlsx', index=False)

In [85]:
df7

,dateOfSleep_119,startTime_119,endTime_119,mainSleep,dateOfSleep_120,startTime_120,endTime_120,mainSleep
0,2024-01-16,2024-01-16 02:37:30,2024-01-16 09:46:30,True,2024-01-16,2024-01-16 01:46:00,2024-01-16 09:59:00,True
1,2024-01-17,2024-01-17 02:41:30,2024-01-17 09:59:00,True,2024-01-17,2024-01-17 02:39:00,2024-01-17 08:00:30,True
2,2024-01-18,2024-01-18 02:29:30,2024-01-18 09:49:00,True,2024-01-18,2024-01-18 02:22:00,2024-01-18 09:42:30,True
3,2024-01-18,2024-01-18 11:40:30,2024-01-18 13:00:30,False,2024-01-19,2024-01-19 17:25:30,2024-01-19 18:37:30,False
4,2024-01-19,2024-01-19 17:25:00,2024-01-19 18:37:30,False,2024-01-19,2024-01-19 01:48:00,2024-01-19 09:02:30,True
5,2024-01-19,2024-01-19 01:45:00,2024-01-19 09:06:00,True,2024-01-20,2024-01-20 06:09:00,2024-01-20 13:20:00,True
6,2024-01-20,2024-01-20 06:16:30,2024-01-20 13:11:00,True,2024-01-21,2024-01-21 01:13:00,2024-01-21 05:59:30,True
7,2024-01-21,2024-01-21 15:12:30,2024-01-21 17:36:30,False,2024-01-22,2024-01-22 00:44:00,2024-01-22 08:02:30,True
8,2024-01-21,2024-01-21 01:13:00,2024-01-21 05:52:30,True,2024-01-23,2024-01-23 01:39:00,2024-01-23 08:03:00,True
9,2024-01-22,2024-01-22 00:54:30,2024-01-22 11:49:00,True,2024-01-24,2024-01-24 08:39:00,2024-01-24 09:51:00,False
10,2024-01-23,2024-01-23 11:18:30,2024-01-23 13:54:30,False,2024-01-24,2024-01-24 01:10:00,2024-01-24 07:26:00,True
11,2024-01-23,2024-01-23 01:37:30,2024-01-23 07:50:00,True,2024-01-25,2024-01-25 01:01:30,2024-01-25 08:06:30,True
12,2024-01-24,2024-01-24 15:20:00,2024-01-24 17:27:30,False,2024-01-26,2024-01-26 03:46:00,2024-01-26 10:08:30,True
13,2024-01-24,2024-01-24 01:23:00,2024-01-24 07:15:00,True,2024-01-27,2024-01-27 03:07:30,2024-01-27 11:56:00,True
14,2024-01-25,2024-01-25 01:10:30,2024-01-25 11:16:30,True,2024-01-28,2024-01-28 02:22:00,2024-01-28 08:04:30,True
15,2024-01-26,2024-01-26 03:49:00,2024-01-26 10:02:00,True,2024-01-29,2024-01-29 01:21:30,2024-01-29 08:12:00,True
16,2024-01-27,2024-01-27 03:57:00,2024-01-27 11:56:00,True,2024-01-29,2024-01-29 01:21:30,2024-01-29 08:12:00,True
17,2024-01-28,2024-01-28 02:23:00,2024-01-28 12:56:00,True,2024-01-30,2024-01-30 01:25:00,2024-01-30 08:02:30,True
18,2024-01-29,2024-01-29 01:17:30,2024-01-29 15:40:00,True,2024-01-31,2024-01-31 00:48:00,2024-01-31 07:59:00,True
19,2024-01-29,2024-01-29 01:17:30,2024-01-29 15:40:00,True,2024-02-01,2024-02-01 02:45:30,2024-02-01 08:32:30,True
20,2024-01-30,2024-01-30 01:26:30,2024-01-30 11:24:00,True,2024-02-02,2024-02-02 03:14:00,2024-02-02 12:39:00,True
21,2024-01-31,2024-01-31 01:05:30,2024-01-31 11:52:30,True,2024-02-03,2024-02-03 04:47:30,2024-02-03 13:22:00,True
22,2024-02-01,2024-02-01 02:47:30,2024-02-01 14:00:00,True,2024-02-04,2024-02-04 02:31:30,2024-02-04 07:49:30,True
23,2024-02-02,2024-02-02 03:46:00,2024-02-02 12:39:00,True,2024-02-05,2024-02-05 01:24:00,2024-02-05 08:01:00,True
24,2024-02-03,2024-02-03 05:00:00,2024-02-03 13:17:30,True,2024-02-06,2024-02-06 03:39:00,2024-02-06 06:01:30,True
25,2024-02-04,2024-02-04 02:41:30,2024-02-04 06:28:30,True,2024-02-07,2024-02-06 21:30:00,2024-02-07 05:56:30,True
26,2024-02-05,2024-02-05 01:24:00,2024-02-05 13:15:00,True,2024-02-08,2024-02-07 23:41:00,2024-02-08 07:19:00,True
27,2024-02-06,2024-02-06 07:52:00,2024-02-06 10:26:30,True,2024-02-09,2024-02-09 00:23:00,2024-02-09 07:36:30,True
28,2024-02-06,2024-02-06 03:39:30,2024-02-06 05:55:00,False,2024-02-10,2024-02-10 05:44:00,2024-02-10 10:41:00,True
29,2024-02-07,2024-02-06 21:39:00,2024-02-07 05:55:30,True,2024-02-16,2024-02-16 05:05:00,2024-02-16 10:43:00,True
30,2024-02-08,2024-02-07 23:47:00,2024-02-08 06:23:30,True,2024-02-17,2024-02-17 03:32:00,2024-02-17 08:56:00,True
31,2024-02-09,2024-02-09 00:37:30,2024-02-09 07:50:30,True,2024-02-18,2024-02-18 08:16:00,2024-02-18 10:31:00,False
32,2024-02-10,2024-02-10 20:37:00,2024-02-10 21:39:00,False,2024-02-18,2024-02-17 21:44:30,2024-02-18 00:51:30,True
33,2024-02-10,2024-02-10 05:42:30,2024-02-10 10:41:30,True,2024-02-19,2024-02-19 19:46:00,2024-02-19 22:56:30,False
34,2024-02-11,2024-02-11 04:42:00,2024-02-11 08:33:00,True,2024-02-19,2024-02-19 00:57:30,2024-02-19 07:52:00,True

In [77]:
subjects_dates = pd.read_csv('/Users/edeneldar/Library/CloudStorage/GoogleDrive-admonlab_edene_hipaa@labs.hevra.haifa.ac.il/תיקיות אחסון שיתופי/Hevra - Roy Salomon Lab - HIPAA/SafeHeart_research_(NovaHelp)/Experiment/Processed Data/Metadata/Subjects Dates.csv')
subjects_dates = pd.DataFrame(subjects_dates)
type(subjects_dates)

pandas.core.frame.DataFrame

In [78]:
subjects_dates.index = subjects_dates['Id']
subjects_dates.drop('Id', axis=1, inplace=True)
subjects_dates

,ExperimentStartDate,ExperimentStartTime,ExperimentEndDate,ExperimentEndTime,Device
Id,,,,,
sub_034,03/12/2023,14:57,05/01/2024,19:00,novastudy_034@labs.hevra.haifa.ac.il
sub_041,03/12/2023,14:40,07/01/2024,12:50,novastudy_041@labs.hevra.haifa.ac.il
sub_048,03/12/2023,14:40,04/01/2024,16:10,novastudy_048@labs.hevra.haifa.ac.il
sub_026,03/12/2023,15:32,03/01/2024,21:50,novastudy_026@labs.hevra.haifa.ac.il
sub_070,03/12/2023,15:10,08/01/2024,19:15,novastudy_070@labs.hevra.haifa.ac.il
...,...,...,...,...,...
C044,08/02/2024,16:50,14/03/2024,18:30,novastudy_039@labs.hevra.haifa.ac.il
C037,08/02/2024,17:00,10/03/2024,8:30,novastudy_031@labs.hevra.haifa.ac.il
E168,11/02/2024,14:30,13/03/2024,18:00,novastudy_028@labs.hevra.haifa.ac.il
E249,14/02/2024,12:20,16/03/2024,8:30,novastudy_055@labs.hevra.haifa.ac.il
E178,14/02/2024,13:04,17/03/2024,14:00,novastudy_024@labs.hevra.haifa.ac.il

In [79]:
subjects_dates = subjects_dates.to_dict()

In [15]:
# get a window to select the start and end dates for a specific subject
def get_dates():
    subject = simpledialog.askstring('Subject', 'Enter subject ID')
    if subject in subjects_dates['ExperimentStartDate']:
        start_date = subjects_dates['ExperimentStartDate'][subject]
        end_date = subjects_dates['ExperimentEndDate'][subject]
        return start_date, end_date
    else:
        return None, None

In [80]:
def get_time_range():
    subject = simpledialog.askstring('Subject', 'Enter subject ID')
    if subject in subjects_dates['ExperimentStartDate']:
        start_date = subjects_dates['ExperimentStartDate'][subject]
        end_date = subjects_dates['ExperimentEndDate'][subject]
        start_time = subjects_dates['ExperimentStartTime'][subject]
        end_time = subjects_dates['ExperimentEndTime'][subject]
        return start_date, end_date, start_time, end_time
    else:
        return None, None, None, None

In [81]:
start_date, end_date, start_time, end_time = get_time_range()

In [82]:
start_date, end_date, start_time, end_time

('15/01/2024', '17/02/2024', '20:40', '17:40')

In [102]:
df7['dateOfSleep_119'] = pd.to_datetime(df7['dateOfSleep_119'])
df7['dateOfSleep_120'] = pd.to_datetime(df7['dateOfSleep_120'])

df7['startTime_119'] = pd.to_datetime(df7['startTime_119'])
df7['startTime_120'] = pd.to_datetime(df7['startTime_120'])

df7['endTime_119'] = pd.to_datetime(df7['endTime_119'])
df7['endTime_120'] = pd.to_datetime(df7['endTime_120'])

In [87]:
df7.columns

Index(['dateOfSleep_119', 'startTime_119', 'endTime_119', 'mainSleep',
       'dateOfSleep_120', 'startTime_120', 'endTime_120', 'mainSleep'],
      dtype='object')

In [89]:
df7.sort_values('dateOfSleep_120', inplace=True)

In [103]:
df7['startTime_119'] = df7['startTime_119'].dt.time
df7['startTime_120'] = df7['startTime_120'].dt.time

df7['endTime_119'] = df7['endTime_119'].dt.time
df7['endTime_120'] = df7['endTime_120'].dt.time

In [104]:
start_date = pd.to_datetime(start_date)
end_date = pd.to_datetime(end_date)
start_time = pd.to_datetime(start_time)
end_time = pd.to_datetime(end_time)

In [105]:
# add a column that iterates over the dates and if there is a date that is missing, it will be added to the dataframe with the value of np.nan
dates = pd.date_range(start_date, "2024-02-22", freq='D')
dates = pd.DataFrame({'dateOfSleep': dates})
dates['dateOfSleep'] = pd.to_datetime(dates['dateOfSleep'])

# outer join the dates with the dataframe to add the missing dates to the dataframe
df7 = pd.merge(dates, df7, how='outer', left_on='dateOfSleep', right_on='dateOfSleep_119')

df7

,dateOfSleep,dateOfSleep_119,startTime_119,endTime_119,mainSleep,dateOfSleep_120,startTime_120,endTime_120,mainSleep
0,2024-01-15,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,2024-01-16,2024-01-16,02:37:30,09:46:30,True,2024-01-16,01:46:00,09:59:00,True
2,2024-01-17,2024-01-17,02:41:30,09:59:00,True,2024-01-17,02:39:00,08:00:30,True
3,2024-01-18,2024-01-18,02:29:30,09:49:00,True,2024-01-18,02:22:00,09:42:30,True
4,2024-01-18,2024-01-18,11:40:30,13:00:30,False,2024-01-19,17:25:30,18:37:30,False
5,2024-01-19,2024-01-19,17:25:00,18:37:30,False,2024-01-19,01:48:00,09:02:30,True
6,2024-01-19,2024-01-19,01:45:00,09:06:00,True,2024-01-20,06:09:00,13:20:00,True
7,2024-01-20,2024-01-20,06:16:30,13:11:00,True,2024-01-21,01:13:00,05:59:30,True
8,2024-01-21,2024-01-21,15:12:30,17:36:30,False,2024-01-22,00:44:00,08:02:30,True
9,2024-01-21,2024-01-21,01:13:00,05:52:30,True,2024-01-23,01:39:00,08:03:00,True
10,2024-01-22,2024-01-22,00:54:30,11:49:00,True,2024-01-24,08:39:00,09:51:00,False
11,2024-01-23,2024-01-23,11:18:30,13:54:30,False,2024-01-24,01:10:00,07:26:00,True
12,2024-01-23,2024-01-23,01:37:30,07:50:00,True,2024-01-25,01:01:30,08:06:30,True
13,2024-01-24,2024-01-24,15:20:00,17:27:30,False,2024-01-26,03:46:00,10:08:30,True
14,2024-01-24,2024-01-24,01:23:00,07:15:00,True,2024-01-27,03:07:30,11:56:00,True
15,2024-01-25,2024-01-25,01:10:30,11:16:30,True,2024-01-28,02:22:00,08:04:30,True
16,2024-01-26,2024-01-26,03:49:00,10:02:00,True,2024-01-29,01:21:30,08:12:00,True
17,2024-01-27,2024-01-27,03:57:00,11:56:00,True,2024-01-29,01:21:30,08:12:00,True
18,2024-01-28,2024-01-28,02:23:00,12:56:00,True,2024-01-30,01:25:00,08:02:30,True
19,2024-01-29,2024-01-29,01:17:30,15:40:00,True,2024-01-31,00:48:00,07:59:00,True
20,2024-01-29,2024-01-29,01:17:30,15:40:00,True,2024-02-01,02:45:30,08:32:30,True
21,2024-01-30,2024-01-30,01:26:30,11:24:00,True,2024-02-02,03:14:00,12:39:00,True
22,2024-01-31,2024-01-31,01:05:30,11:52:30,True,2024-02-03,04:47:30,13:22:00,True
23,2024-02-01,2024-02-01,02:47:30,14:00:00,True,2024-02-04,02:31:30,07:49:30,True
24,2024-02-02,2024-02-02,03:46:00,12:39:00,True,2024-02-05,01:24:00,08:01:00,True
25,2024-02-03,2024-02-03,05:00:00,13:17:30,True,2024-02-06,03:39:00,06:01:30,True
26,2024-02-04,2024-02-04,02:41:30,06:28:30,True,2024-02-07,21:30:00,05:56:30,True
27,2024-02-05,2024-02-05,01:24:00,13:15:00,True,2024-02-08,23:41:00,07:19:00,True
28,2024-02-06,2024-02-06,07:52:00,10:26:30,True,2024-02-09,00:23:00,07:36:30,True
29,2024-02-06,2024-02-06,03:39:30,05:55:00,False,2024-02-10,05:44:00,10:41:00,True
30,2024-02-07,2024-02-07,21:39:00,05:55:30,True,2024-02-16,05:05:00,10:43:00,True
31,2024-02-08,2024-02-08,23:47:00,06:23:30,True,2024-02-17,03:32:00,08:56:00,True
32,2024-02-09,2024-02-09,00:37:30,07:50:30,True,2024-02-18,08:16:00,10:31:00,False
33,2024-02-10,2024-02-10,20:37:00,21:39:00,False,2024-02-18,21:44:30,00:51:30,True
34,2024-02-10,2024-02-10,05:42:30,10:41:30,True,2024-02-19,19:46:00,22:56:30,False
35,2024-02-11,2024-02-11,04:42:00,08:33:00,True,2024-02-19,00:57:30,07:52:00,True
36,2024-02-12,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
37,2024-02-13,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
38,2024-02-14,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
39,2024-02-15,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
40,2024-02-16,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
41,2024-02-17,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
42,2024-02-18,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
43,2024-02-19,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
44,2024-02-20,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
45,2024-02-21,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
46,2024-02-22,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [25]:
df3_time

,logId,dateOfSleep,startTime,endTime,duration,minutesToFallAsleep,minutesAsleep,minutesAwake,minutesAfterWakeup,timeInBed,efficiency,type,infoCode,logType,levels,mainSleep
18,44255581065,2024-01-16,2024-01-16 02:37:30,09:46:30,25740000,0,359,70,0,429,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 3...",True
17,44255581066,2024-01-17,2024-01-17 02:41:30,09:59:00,26220000,0,353,84,0,437,91,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 7...",True
16,44255581067,2024-01-18,2024-01-18 02:29:30,09:49:00,26340000,0,394,45,1,439,84,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 8...",True
15,44255581068,2024-01-18,2024-01-18 11:40:30,13:00:30,4800000,0,73,7,0,80,91,classic,2,auto_detected,"{'summary': {'restless': {'count': 3, 'minutes...",False
13,44255581070,2024-01-19,2024-01-19 17:25:00,18:37:30,4320000,0,64,8,0,72,89,classic,2,auto_detected,"{'summary': {'restless': {'count': 4, 'minutes...",False
14,44255581069,2024-01-19,2024-01-19 01:45:00,09:06:00,26460000,0,379,62,0,441,85,stages,0,auto_detected,"{'summary': {'deep': {'count': 6, 'minutes': 8...",True
12,44255581071,2024-01-20,2024-01-20 06:16:30,13:11:00,24840000,0,356,58,8,414,89,stages,0,auto_detected,"{'summary': {'deep': {'count': 2, 'minutes': 7...",True
10,44255581073,2024-01-21,2024-01-21 15:12:30,17:36:30,8640000,0,130,14,0,144,90,classic,2,auto_detected,"{'summary': {'restless': {'count': 6, 'minutes...",False
11,44255581072,2024-01-21,2024-01-21 01:13:00,05:52:30,16740000,0,253,26,6,279,92,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 6...",True
9,44313852626,2024-01-22,2024-01-22 00:54:30,11:49:00,39240000,0,582,72,0,654,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 8, 'minutes': 1...",True
7,44313852628,2024-01-23,2024-01-23 11:18:30,13:54:30,9360000,0,139,17,0,156,89,classic,2,auto_detected,"{'summary': {'restless': {'count': 8, 'minutes...",False
8,44313852627,2024-01-23,2024-01-23 01:37:30,07:50:00,22320000,0,339,33,0,372,88,stages,0,auto_detected,"{'summary': {'deep': {'count': 2, 'minutes': 7...",True
5,44313852630,2024-01-24,2024-01-24 15:20:00,17:27:30,7620000,0,113,9,5,127,93,classic,2,auto_detected,"{'summary': {'restless': {'count': 3, 'minutes...",False
6,44313852629,2024-01-24,2024-01-24 01:23:00,07:15:00,21120000,0,317,35,0,352,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 6...",True
4,44313852631,2024-01-25,2024-01-25 01:10:30,11:16:30,36360000,0,550,56,0,606,92,stages,0,auto_detected,"{'summary': {'deep': {'count': 6, 'minutes': 8...",True
3,44313852632,2024-01-26,2024-01-26 03:49:00,10:02:00,22380000,0,329,44,1,373,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 6...",True
2,44378891523,2024-01-27,2024-01-27 03:57:00,11:56:00,28740000,0,444,35,0,479,96,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 1...",True
1,44378891524,2024-01-28,2024-01-28 02:23:00,12:56:00,37980000,0,545,88,2,633,88,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 8...",True
0,44378891525,2024-01-29,2024-01-29 01:17:30,15:40:00,51720000,0,709,153,0,862,82,stages,0,auto_detected,"{'summary': {'deep': {'count': 7, 'minutes': 6...",True
15,44378891525,2024-01-29,2024-01-29 01:17:30,15:40:00,51720000,0,709,153,0,862,82,stages,0,auto_detected,"{'summary': {'deep': {'count': 7, 'minutes': 6...",True
14,44378891526,2024-01-30,2024-01-30 01:26:30,11:24:00,35820000,0,531,66,0,597,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 9...",True
13,44378891527,2024-01-31,2024-01-31 01:05:30,11:52:30,38820000,0,557,90,0,647,89,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 7...",True
12,44434654834,2024-02-01,2024-02-01 02:47:30,14:00:00,40320000,0,575,97,1,672,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 7, 'minutes': 1...",True
11,44434654835,2024-02-02,2024-02-02 03:46:00,12:39:00,31980000,0,485,48,0,533,93,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 1...",True
10,44434654836,2024-02-03,2024-02-03 05:00:00,13:17:30,29820000,0,433,64,0,497,88,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 9...",True
9,44434654837,2024-02-04,2024-02-04 02:41:30,06:28:30,13620000,0,202,25,0,227,91,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 3...",True
8,44434654838,2024-02-05,2024-02-05 01:24:00,13:15:00,42660000,0,609,102,0,711,91,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 9...",True
6,44446555897,2024-02-06,2024-02-06 07:52:00,10:26:30,9240000,0,137,17,0,154,89,classic,2,auto_detected,"{'summary': {'restless': {'count': 8, 'minutes...",True
7,44446555896,2024-02-06,2024-02-06 03:39:30,05:55:00,8100000,0,122,13,0,135,90,classic,2,auto_detected,"{'summary': {'restless': {'count': 7, 'minutes...",False
5,44503259494,2024-02-07,2024-02-06 21:39:00,05:55:30,29760000,0,450,46,5,496,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 6...",True
4,44503259495,2024-02-08,2024-02-07 23:47:00,06:23:30,23760000,0,362,34,0,396,96,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 7...",True
3,44503259496,2024-02-09,2024-02-09 00:37:30,07:50:30,25980000,0,403,30,0,433,95,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 6...",True
1,44503259498,2024-02-10,2024-02-10 20:37:00,21:39:00,3720000,0,58,4,0,62,94,classic,2,auto_detected,"{'summary': {'restless': {'count': 2, 'minutes...",False
2,44503259497,2024-02-10,2024-02-10 05:42:30,10:41:30,17940000,0,277,22,0,299,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 7...",True
0,44503259499,2024-02-11,2024-02-11 04:42:00,08:33:00,13860000,0,200,31,0,231,93,stages,0,auto_detected,"{'summary': {'deep': {'count': 2, 'minutes': 6...",True

In [26]:
# check for missing dates
dates = pd.date_range(start_date, end_date)
missing_dates = []
for date in dates:
    if date not in df3_time['dateOfSleep'].values:
        missing_dates.append(date)
missing_dates

[Timestamp('2024-01-15 00:00:00'),
 Timestamp('2024-02-12 00:00:00'),
 Timestamp('2024-02-13 00:00:00'),
 Timestamp('2024-02-14 00:00:00'),
 Timestamp('2024-02-15 00:00:00'),
 Timestamp('2024-02-16 00:00:00'),
 Timestamp('2024-02-17 00:00:00')]

In [27]:
start_date, end_date

(Timestamp('2024-01-15 00:00:00'), Timestamp('2024-02-17 00:00:00'))

In [30]:
# get a dataframe with the sleep times and dates from df3_time
df3_time['startTime'] = df3_time['startTime'].dt.time

In [31]:
df3_time

,logId,dateOfSleep,startTime,endTime,duration,minutesToFallAsleep,minutesAsleep,minutesAwake,minutesAfterWakeup,timeInBed,efficiency,type,infoCode,logType,levels,mainSleep
18,44255581065,2024-01-16,02:37:30,09:46:30,25740000,0,359,70,0,429,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 3...",True
17,44255581066,2024-01-17,02:41:30,09:59:00,26220000,0,353,84,0,437,91,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 7...",True
16,44255581067,2024-01-18,02:29:30,09:49:00,26340000,0,394,45,1,439,84,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 8...",True
15,44255581068,2024-01-18,11:40:30,13:00:30,4800000,0,73,7,0,80,91,classic,2,auto_detected,"{'summary': {'restless': {'count': 3, 'minutes...",False
13,44255581070,2024-01-19,17:25:00,18:37:30,4320000,0,64,8,0,72,89,classic,2,auto_detected,"{'summary': {'restless': {'count': 4, 'minutes...",False
14,44255581069,2024-01-19,01:45:00,09:06:00,26460000,0,379,62,0,441,85,stages,0,auto_detected,"{'summary': {'deep': {'count': 6, 'minutes': 8...",True
12,44255581071,2024-01-20,06:16:30,13:11:00,24840000,0,356,58,8,414,89,stages,0,auto_detected,"{'summary': {'deep': {'count': 2, 'minutes': 7...",True
10,44255581073,2024-01-21,15:12:30,17:36:30,8640000,0,130,14,0,144,90,classic,2,auto_detected,"{'summary': {'restless': {'count': 6, 'minutes...",False
11,44255581072,2024-01-21,01:13:00,05:52:30,16740000,0,253,26,6,279,92,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 6...",True
9,44313852626,2024-01-22,00:54:30,11:49:00,39240000,0,582,72,0,654,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 8, 'minutes': 1...",True
7,44313852628,2024-01-23,11:18:30,13:54:30,9360000,0,139,17,0,156,89,classic,2,auto_detected,"{'summary': {'restless': {'count': 8, 'minutes...",False
8,44313852627,2024-01-23,01:37:30,07:50:00,22320000,0,339,33,0,372,88,stages,0,auto_detected,"{'summary': {'deep': {'count': 2, 'minutes': 7...",True
5,44313852630,2024-01-24,15:20:00,17:27:30,7620000,0,113,9,5,127,93,classic,2,auto_detected,"{'summary': {'restless': {'count': 3, 'minutes...",False
6,44313852629,2024-01-24,01:23:00,07:15:00,21120000,0,317,35,0,352,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 6...",True
4,44313852631,2024-01-25,01:10:30,11:16:30,36360000,0,550,56,0,606,92,stages,0,auto_detected,"{'summary': {'deep': {'count': 6, 'minutes': 8...",True
3,44313852632,2024-01-26,03:49:00,10:02:00,22380000,0,329,44,1,373,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 6...",True
2,44378891523,2024-01-27,03:57:00,11:56:00,28740000,0,444,35,0,479,96,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 1...",True
1,44378891524,2024-01-28,02:23:00,12:56:00,37980000,0,545,88,2,633,88,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 8...",True
0,44378891525,2024-01-29,01:17:30,15:40:00,51720000,0,709,153,0,862,82,stages,0,auto_detected,"{'summary': {'deep': {'count': 7, 'minutes': 6...",True
15,44378891525,2024-01-29,01:17:30,15:40:00,51720000,0,709,153,0,862,82,stages,0,auto_detected,"{'summary': {'deep': {'count': 7, 'minutes': 6...",True
14,44378891526,2024-01-30,01:26:30,11:24:00,35820000,0,531,66,0,597,90,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 9...",True
13,44378891527,2024-01-31,01:05:30,11:52:30,38820000,0,557,90,0,647,89,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 7...",True
12,44434654834,2024-02-01,02:47:30,14:00:00,40320000,0,575,97,1,672,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 7, 'minutes': 1...",True
11,44434654835,2024-02-02,03:46:00,12:39:00,31980000,0,485,48,0,533,93,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 1...",True
10,44434654836,2024-02-03,05:00:00,13:17:30,29820000,0,433,64,0,497,88,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 9...",True
9,44434654837,2024-02-04,02:41:30,06:28:30,13620000,0,202,25,0,227,91,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 3...",True
8,44434654838,2024-02-05,01:24:00,13:15:00,42660000,0,609,102,0,711,91,stages,0,auto_detected,"{'summary': {'deep': {'count': 5, 'minutes': 9...",True
6,44446555897,2024-02-06,07:52:00,10:26:30,9240000,0,137,17,0,154,89,classic,2,auto_detected,"{'summary': {'restless': {'count': 8, 'minutes...",True
7,44446555896,2024-02-06,03:39:30,05:55:00,8100000,0,122,13,0,135,90,classic,2,auto_detected,"{'summary': {'restless': {'count': 7, 'minutes...",False
5,44503259494,2024-02-07,21:39:00,05:55:30,29760000,0,450,46,5,496,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 6...",True
4,44503259495,2024-02-08,23:47:00,06:23:30,23760000,0,362,34,0,396,96,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 7...",True
3,44503259496,2024-02-09,00:37:30,07:50:30,25980000,0,403,30,0,433,95,stages,0,auto_detected,"{'summary': {'deep': {'count': 4, 'minutes': 6...",True
1,44503259498,2024-02-10,20:37:00,21:39:00,3720000,0,58,4,0,62,94,classic,2,auto_detected,"{'summary': {'restless': {'count': 2, 'minutes...",False
2,44503259497,2024-02-10,05:42:30,10:41:30,17940000,0,277,22,0,299,94,stages,0,auto_detected,"{'summary': {'deep': {'count': 3, 'minutes': 7...",True
0,44503259499,2024-02-11,04:42:00,08:33:00,13860000,0,200,31,0,231,93,stages,0,auto_detected,"{'summary': {'deep': {'count': 2, 'minutes': 6...",True

In [65]:
steps1 = r'/Users/edeneldar/Library/CloudStorage/GoogleDrive-admonlab_edene_hipaa@labs.hevra.haifa.ac.il/תיקיות אחסון שיתופי/Hevra - Roy Salomon Lab - HIPAA/SafeHeart_research_(NovaHelp)/Experiment/Data/sub_119/FITBIT/Physical Activity/steps-2023-12-30.json'
steps2 = r'/Users/edeneldar/Library/CloudStorage/GoogleDrive-admonlab_edene_hipaa@labs.hevra.haifa.ac.il/תיקיות אחסון שיתופי/Hevra - Roy Salomon Lab - HIPAA/SafeHeart_research_(NovaHelp)/Experiment/Data/sub_119/FITBIT/Physical Activity/steps-2024-01-29.json'

steps4 = r''
with open(steps1, 'r') as f:
    steps1 = json.load(f)

with open(steps2, 'r') as f:
    steps2 = json.load(f)
    
steps1 = pd.DataFrame(steps1)
steps2 = pd.DataFrame(steps2)

steps = chain_data(steps1, steps2)

steps

                dateTime value
0      01/15/24 18:44:00     0
1      01/15/24 18:45:00     0
2      01/15/24 18:50:00     0
3      01/15/24 18:51:00     0
4      01/15/24 18:53:00     8
...                  ...   ...
15146  02/18/24 01:39:00     6
15147  02/18/24 01:40:00     0
15148  02/18/24 01:41:00     0
15149  02/18/24 01:42:00     0
15150  02/18/24 01:45:00     0

[24686 rows x 2 columns]

In [66]:
# Get the segments of steps data by date starting time and ending time
steps_dict = {}

steps['dateTime'] = pd.to_datetime(steps['dateTime'])
steps['time'] = steps['dateTime'].dt.time
steps['date'] = steps['dateTime'].dt.date

steps['time'] = steps['time'].apply(lambda x: x.strftime('%H:%M:%S'))
steps['date'] = steps['date'].apply(lambda x: x.strftime('%Y-%m-%d'))

steps

/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/4248727030.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps['dateTime'] = pd.to_datetime(steps['dateTime'])

                 dateTime value      time        date
0     2024-01-15 18:44:00     0  18:44:00  2024-01-15
1     2024-01-15 18:45:00     0  18:45:00  2024-01-15
2     2024-01-15 18:50:00     0  18:50:00  2024-01-15
3     2024-01-15 18:51:00     0  18:51:00  2024-01-15
4     2024-01-15 18:53:00     8  18:53:00  2024-01-15
...                   ...   ...       ...         ...
15146 2024-02-18 01:39:00     6  01:39:00  2024-02-18
15147 2024-02-18 01:40:00     0  01:40:00  2024-02-18
15148 2024-02-18 01:41:00     0  01:41:00  2024-02-18
15149 2024-02-18 01:42:00     0  01:42:00  2024-02-18
15150 2024-02-18 01:45:00     0  01:45:00  2024-02-18

[24686 rows x 4 columns]

In [40]:
# keep only the times of each date in the dictionary
for date in steps_dict:
    steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
    
steps_dict

/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  steps_dict[date]['dateTime'] = pd.to_datetime(steps_dict[date]['dateTime']).dt.time
/var/folders/5g/7gzv8rg14tv7prkqk0v2f3280000gn/T/ipykernel_38127/3503217149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


{'01/15/24':      dateTime value
 0    18:44:00     0
 1    18:45:00     0
 2    18:50:00     0
 3    18:51:00     0
 4    18:53:00     8
 ..        ...   ...
 232  23:44:00     0
 233  23:45:00     7
 234  23:50:00     0
 235  23:51:00     6
 236  23:52:00     0

 [237 rows x 2 columns],
 '01/16/24':       dateTime value
 237   00:10:00     0
 238   00:12:00     0
 239   00:22:00     0
 240   00:23:00     0
 241   00:25:00     0
 ...        ...   ...
 1051  23:55:00     0
 1052  23:56:00     0
 1053  23:57:00     0
 1054  23:58:00     0
 1055  23:59:00     0

 [819 rows x 2 columns],
 '01/17/24':       dateTime value
 1056  00:00:00     0
 1057  00:01:00     0
 1058  00:02:00     0
 1059  00:04:00     0
 1060  00:05:00     0
 ...        ...   ...
 1829  23:31:00     0
 1830  23:38:00     0
 1831  23:44:00     0
 1832  23:58:00     0
 1833  23:59:00    10

 [778 rows x 2 columns],
 '01/18/24':       dateTime value
 1834  00:00:00     0
 1835  00:01:00     6
 1836  00:02:00     0
 1837  00:03:00    18
 1838  00:04:00     8
 ...        ...   ...
 2406  23:29:00     6
 2407  23:39:00     5
 2408  23:40:00     9
 2409  23:41:00     5
 2410  23:44:00    17

 [577 rows x 2 columns],
 '01/19/24':       dateTime value
 2411  00:00:00    16
 2412  00:01:00     0
 2413  01:00:00     0
 2414  01:01:00     0
 2415  01:02:00     0
 ...        ...   ...
 3137  23:54:00     0
 3138  23:56:00     8
 3139  23:57:00     0
 3140  23:58:00    13
 3141  23:59:00     0

 [731 rows x 2 columns],
 '01/20/24':       dateTime value
 3142  00:00:00    10
 3143  00:01:00    20
 3144  00:02:00    14
 3145  00:03:00    16
 3146  00:04:00     5
 ...        ...   ...
 4048  23:13:00     0
 4049  23:27:00     0
 4050  23:50:00     0
 4051  23:51:00     0
 4052  23:52:00    13

 [911 rows x 2 columns],
 '01/21/24':       dateTime value
 4053  00:21:00     0
 4054  00:22:00     0
 4055  00:33:00     0
 4056  00:41:00     0
 4057  00:52:00     0
 ...        ...   ...
 4783  22:49:00     9
 4784  23:02:00     0
 4785  23:12:00     4
 4786  23:51:00    17
 4787  23:54:00     0

 [735 rows x 2 columns],
 '01/22/24':       dateTime value
 4788  00:40:00     0
 4789  02:08:00     0
 4790  02:14:00     0
 4791  02:23:00     0
 4792  02:26:00     0
 ...        ...   ...
 5429  23:33:00    10
 5430  23:34:00    44
 5431  23:35:00    24
 5432  23:36:00     0
 5433  23:52:00    15

 [646 rows x 2 columns],
 '01/23/24':       dateTime value
 5434  00:46:00     0
 5435  00:52:00     0
 5436  01:04:00     0
 5437  01:26:00    10
 5438  02:13:00     0
 ...        ...   ...
 5981  23:23:00     0
 5982  23:24:00     0
 5983  23:30:00     0
 5984  23:39:00     0
 5985  23:47:00     0

 [552 rows x 2 columns],
 '01/24/24':       dateTime value
 5986  00:00:00     0
 5987  00:01:00    11
 5988  00:38:00     0
 5989  01:05:00     0
 5990  01:06:00     0
 ...        ...   ...
 6559  22:55:00     0
 6560  22:56:00     6
 6561  22:59:00     0
 6562  23:02:00     0
 6563  23:18:00     0

 [578 rows x 2 columns],
 '01/25/24':       dateTime value
 6564  00:04:00     0
 6565  00:05:00     6
 6566  00:06:00     5
 6567  00:25:00     0
 6568  01:04:00     0
 ...        ...   ...
 7187  23:44:00     0
 7188  23:46:00     0
 7189  23:49:00     0
 7190  23:58:00     0
 7191  23:59:00     0

 [628 rows x 2 columns],
 '01/26/24':       dateTime value
 7192  00:00:00     0
 7193  00:01:00     0
 7194  00:02:00     0
 7195  00:03:00     0
 7196  00:04:00     7
 ...        ...   ...
 8130  23:53:00     0
 8131  23:55:00     0
 8132  23:56:00    14
 8133  23:57:00     0
 8134  23:58:00     8

 [943 rows x 2 columns],
 '01/27/24':       dateTime value
 8135  00:00:00     0
 8136  00:01:00     0
 8137  00:02:00     0
 8138  00:03:00     0
 8139  00:04:00     0
 ...        ...   ...
 8933  23:52:00     0
 8934  23:53:00     0
 8935  23:54:00     0
 8936  23:57:00     0
 8937  23:58:00     0

 [803 rows x 2 columns],
 '01/28/24':       dateTime value
 8938  00:00:00     0
 8939  00:02:00     0
 8940  00:03:00     0
 8941  00:04:00    18
 8942  00:05:00     0
 ...        ...   ...
 68    23:50:00     0
 69    23:51:00     0
 70    23:52:00     0
 71    23:53:00     0
 72    23:54:00    12

 [670 rows x 2 columns],
 '01/29/24':      dateTime value
 73   00:02:00     0
 74   00:11:00     0
 75   00:21:00     0
 76   00:23:00     0
 77   00:24:00     0
 ..        ...   ...
 588  23:19:00     0
 589  23:20:00     0
 590  23:22:00     0
 591  23:47:00     0
 592  23:59:00     0

 [520 rows x 2 columns],
 '01/30/24':       dateTime value
 593   00:32:00     0
 594   00:33:00     0
 595   00:34:00     0
 596   00:50:00     0
 597   00:51:00     6
 ...        ...   ...
 1230  23:14:00     8
 1231  23:15:00     0
 1232  23:16:00     0
 1233  23:20:00     9
 1234  23:35:00     0

 [642 rows x 2 columns],
 '01/31/24':       dateTime value
 1235  00:44:00     0
 1236  01:00:00     5
 1237  01:14:00     0
 1238  01:15:00     0
 1239  01:33:00     0
 ...        ...   ...
 1794  23:55:00     0
 1795  23:56:00     0
 1796  23:57:00     0
 1797  23:58:00     0
 1798  23:59:00     0

 [564 rows x 2 columns],
 '02/01/24':       dateTime value
 1799  00:00:00     0
 1800  00:01:00     0
 1801  00:03:00     0
 1802  00:04:00     0
 1803  00:05:00     0
 ...        ...   ...
 2312  23:49:00     0
 2313  23:55:00     0
 2314  23:57:00     0
 2315  23:58:00     0
 2316  23:59:00     7

 [518 rows x 2 columns],
 '02/02/24':       dateTime value
 2317  00:47:00     0
 2318  00:50:00     0
 2319  00:55:00     0
 2320  00:56:00     0
 2321  00:58:00     0
 ...        ...   ...
 2955  23:54:00     0
 2956  23:56:00     0
 2957  23:57:00     0
 2958  23:58:00     0
 2959  23:59:00    24

 [643 rows x 2 columns],
 '02/03/24':       dateTime value
 2960  00:00:00     0
 2961  00:01:00    42
 2962  00:02:00     0
 2963  00:03:00     0
 2964  00:04:00     0
 ...        ...   ...
 3661  23:46:00    10
 3662  23:53:00     0
 3663  23:54:00     0
 3664  23:55:00     5
 3665  23:56:00     0

 [706 rows x 2 columns],
 '02/04/24':       dateTime value
 3666  00:10:00     0
 3667  00:11:00     6
 3668  00:12:00     0
 3669  00:13:00     0
 3670  00:15:00     7
 ...        ...   ...
 4329  23:08:00     0
 4330  23:09:00     0
 4331  23:10:00     0
 4332  23:34:00     8
 4333  23:35:00    11

 [668 rows x 2 columns],
 '02/05/24':       dateTime value
 4334  00:14:00     0
 4335  00:56:00     0
 4336  00:57:00     0
 4337  00:58:00     0
 4338  01:01:00     0
 ...        ...   ...
 4925  23:55:00     0
 4926  23:56:00    14
 4927  23:57:00     0
 4928  23:58:00     0
 4929  23:59:00    12

 [596 rows x 2 columns],
 '02/06/24':       dateTime value
 4930  00:00:00     0
 4931  00:01:00     9
 4932  00:02:00     5
 4933  00:03:00    17
 4934  00:04:00    12
 ...        ...   ...
 5651  19:37:00    76
 5652  19:38:00    64
 5653  19:39:00     9
 5654  19:40:00    15
 5655  19:47:00     0

 [484 rows x 2 columns],
 '02/07/24':       dateTime value
 5333  00:00:00     0
 5334  00:01:00     0
 5335  00:02:00     0
 5336  00:03:00    40
 5337  00:04:00    43
 ...        ...   ...
 6056  23:16:00     0
 6057  23:21:00     0
 6058  23:22:00     0
 6059  23:23:00     0
 6060  23:37:00     0

 [647 rows x 2 columns],
 '02/08/24':       dateTime value
 6061  00:03:00     0
 6062  00:07:00     0
 6063  00:08:00     0
 6064  00:45:00     0
 6065  00:49:00     0
 ...        ...   ...
 6871  23:55:00     0
 6872  23:56:00     0
 6873  23:57:00     0
 6874  23:58:00    10
 6875  23:59:00     0

 [815 rows x 2 columns],
 '02/09/24':       dateTime value
 6876  00:00:00     0
 6877  00:01:00     0
 6878  00:02:00     0
 6879  00:03:00     0
 6880  00:04:00     0
 ...        ...   ...
 7625  23:50:00     0
 7626  23:51:00     0
 7627  23:52:00     0
 7628  23:53:00     0
 7629  23:59:00    20

 [754 rows x 2 columns],
 '02/10/24':       dateTime value
 7630  00:00:00     0
 7631  00:01:00     0
 7632  00:02:00     0
 7633  00:03:00     0
 7634  00:04:00     0
 ...        ...   ...
 8581  23:55:00    24
 8582  23:56:00     0
 8583  23:57:00     0
 8584  23:58:00     0
 8585  23:59:00     0

 [956 rows x 2 columns],
 '02/11/24':       dateTime value
 8586  00:00:00     0
 8587  00:01:00    41
 8588  00:02:00     0
 8589  00:03:00     0
 8590  00:04:00     0
 ...        ...   ...
 9519  23:55:00     4
 9520  23:56:00     0
 9521  23:57:00     0
 9522  23:58:00     7
 9523  23:59:00     0

 [938 rows x 2 columns],
 '02/12/24':        dateTime value
 9524   00:00:00     0
 9525   00:01:00     0
 9526   00:02:00     0
 9527   00:03:00     0
 9528   00:04:00     0
 ...         ...   ...
 10395  23:55:00    17
 10396  23:56:00     8
 10397  23:57:00     0
 10398  23:58:00     0
 10399  23:59:00     0

 [876 rows x 2 columns],
 '02/13/24':        dateTime value
 10400  00:00:00     0
 10401  00:01:00     0
 10402  00:02:00     0
 10403  00:03:00    15
 10404  00:04:00    38
 ...         ...   ...
 11208  23:51:00     0
 11209  23:52:00     0
 11210  23:53:00     7
 11211  23:56:00     0
 11212  23:58:00     0

 [813 rows x 2 columns],
 '02/14/24':        dateTime value
 11213  00:01:00     9
 11214  00:04:00     0
 11215  00:05:00     9
 11216  00:06:00    20
 11217  00:07:00     0
 ...         ...   ...
 12088  23:55:00     0
 12089  23:56:00     7
 12090  23:57:00     6
 12091  23:58:00     0
 12092  23:59:00     9

 [880 rows x 2 columns],
 '02/15/24':        dateTime value
 12093  00:00:00     9
 12094  00:01:00    72
 12095  00:02:00    21
 12096  00:03:00    18
 12097  00:04:00    50
 ...         ...   ...
 13058  23:55:00     0
 13059  23:56:00     0
 13060  23:57:00     0
 13061  23:58:00    25
 13062  23:59:00    36

 [970 rows x 2 columns],
 '02/16/24':        dateTime value
 13063  00:00:00    63
 13064  00:01:00    50
 13065  00:02:00    61
 13066  00:03:00    36
 13067  00:04:00    23
 ...         ...   ...
 14080  23:55:00     0
 14081  23:56:00     0
 14082  23:57:00     5
 14083  23:58:00     0
 14084  23:59:00     0

 [1022 rows x 2 columns],
 '02/17/24':        dateTime value
 14085  00:01:00    15
 14086  00:02:00     0
 14087  00:03:00     0
 14088  00:04:00     0
 14089  00:05:00     0
 ...         ...   ...
 15045  23:55:00     0
 15046  23:56:00     0
 15047  23:57:00    59
 15048  23:58:00    25
 15049  23:59:00     0

 [965 rows x 2 columns],
 '02/18/24':        dateTime value
 15050  00:00:00    10
 15051  00:01:00    87
 15052  00:02:00    49
 15053  00:03:00    29
 15054  00:04:00     2
 ...         ...   ...
 15146  01:39:00     6
 15147  01:40:00     0
 15148  01:41:00     0
 15149  01:42:00     0
 15150  01:45:00     0

 [101 rows x 2 columns]}

In [54]:
# filter only the main sleep times from df3_time
df3_main = [df3_time[df3_time['mainSleep'] == True]]

df3_main = pd.concat(df3_main, axis=0)

steps_dict_main = {}
df3_main['dateOfSleep'] = df3_main['dateOfSleep'].dt.date


for date in df3_main['dateOfSleep'].unique():
    steps_dict_main[date] = steps_dict[str(date)]

KeyError: '2024-01-16'